=== clachi98/ProgettoWebSystem/consegna_palinsesto/src/main/resources/static/palinsesti/palinsesto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definizione del tipo di dati per il nome del file HTML -->
    <xs:simpleType name="htmlFileName">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]+\.[h][t][m][l]"/> <!-- Pattern per i nomi dei file HTML -->
        </xs:restriction>
    </xs:simpleType>

    <!-- Definizione del tipo di dati per la durata -->
    <xs:simpleType name="durationType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/> <!-- La durata deve essere un numero intero positivo -->
        </xs:restriction>
    </xs:simpleType>

    <!-- Definizione del tipo di dati per un singolo cartellone dell'XML -->
    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element name="fileHTML" type="htmlFileName"/>
            <xs:element name="durata" type="durationType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definizione del tipo di dati per l'elenco di elementi -->
    <xs:element name="palinsesto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cartellone" type="itemType" minOccurs="0" maxOccurs="unbounded"/> <!-- Elemento "cartellone" può comparire 0 o più volte -->
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== clachi98/ProgettoWebSystem/consegna_palinsesto/src/main/resources/static/palinsesti/palinsesto2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Se volessimo validare il file XML con il file DTD esterno -->
<!-- <!DOCTYPE palinsesto SYSTEM "palinsesto.dtd"> -->
<!-- Non dovremmo inserire la parte "xmlns" nel tag "palinsesto" -->

<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="palinsesto.xsd">
    <cartellone>
        <fileHTML>dragons.html</fileHTML>
        <durata>8</durata> <!-- Durata in secondi -->
    </cartellone>
    <cartellone>
        <fileHTML>cartoni.html</fileHTML>
        <durata>9</durata>
    </cartellone>
    <cartellone>
        <fileHTML>marziale.html</fileHTML>
        <durata>15</durata>
    </cartellone>
    <cartellone>
        <fileHTML>CocaCola.html</fileHTML>
        <durata>12</durata>
    </cartellone>
</palinsesto>

=== clachi98/ProgettoWebSystem/consegna_palinsesto/src/main/resources/static/palinsesti/palinsesto7.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Se volessimo validare il file XML con il file DTD esterno -->
<!-- <!DOCTYPE palinsesto SYSTEM "palinsesto.dtd"> -->
<!-- Non dovremmo inserire la parte "xmlns" nel tag "palinsesto" -->

<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="palinsesto.xsd">
  <cartellone>
    <fileHTML>NaturaSi.html</fileHTML>
    <durata>10</durata> <!-- Durata in secondi -->
  </cartellone>
  <cartellone>
    <fileHTML>marziale.html</fileHTML>
    <durata>15</durata>
  </cartellone>
  <cartellone>
    <fileHTML>nissan.html</fileHTML>
    <durata>8</durata>
  </cartellone>
</palinsesto>

=== clachi98/ProgettoWebSystem/consegna_palinsesto/src/main/resources/static/palinsesti/palinsesto5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Se volessimo validare il file XML con il file DTD esterno -->
<!-- <!DOCTYPE palinsesto SYSTEM "palinsesto.dtd"> -->
<!-- Non dovremmo inserire la parte "xmlns" nel tag "palinsesto" -->

<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="palinsesto.xsd">
  <cartellone>
    <fileHTML>CocaCola.html</fileHTML>
    <durata>12</durata> <!-- Durata in secondi -->
  </cartellone>
  <cartellone>
    <fileHTML>NaturaSi.html</fileHTML>
    <durata>10</durata>
  </cartellone>
  <cartellone>
    <fileHTML>Vespa.html</fileHTML>
    <durata>10</durata>
  </cartellone>
</palinsesto>

=== clachi98/ProgettoWebSystem/consegna_palinsesto/src/main/resources/static/palinsesti/palinsesto1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Se volessimo validare il file XML con il file DTD esterno -->
<!-- <!DOCTYPE palinsesto SYSTEM "palinsesto.dtd"> -->
<!-- Non dovremmo inserire la parte "xmlns" nel tag "palinsesto" -->

<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="palinsesto.xsd">

    <cartellone>
        <fileHTML>nissan.html</fileHTML>    <!-- Nome del file da richiedere al server -->
        <durata>8</durata>  <!-- Durata in secondi -->
    </cartellone>

    <cartellone>
        <fileHTML>notebook.html</fileHTML>
        <durata>8</durata>
    </cartellone>

    <cartellone>
        <fileHTML>festival.html</fileHTML>
        <durata>9</durata>
    </cartellone>

    <cartellone>
        <fileHTML>dentista.html</fileHTML>
        <durata>22</durata>
    </cartellone>

</palinsesto>

=== clachi98/ProgettoWebSystem/consegna_palinsesto/src/main/resources/static/palinsesti/palinsesto4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Se volessimo validare il file XML con il file DTD esterno -->
<!-- <!DOCTYPE palinsesto SYSTEM "palinsesto.dtd"> -->
<!-- Non dovremmo inserire la parte "xmlns" nel tag "palinsesto" -->

<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="palinsesto.xsd">
    <cartellone>
        <fileHTML>Vespa.html</fileHTML>
        <durata>10</durata> <!-- Durata in secondi -->
    </cartellone>
    <cartellone>
        <fileHTML>nissan.html</fileHTML>
        <durata>8</durata>
    </cartellone>
    <cartellone>
        <fileHTML>cartoni.html</fileHTML>
        <durata>9</durata>
    </cartellone>
</palinsesto>
